Fix forwarding notification opens from non onesignal notifs
OneSignal/OneSignal-iOS-SDK pull request #1131
Opened 2022-10-13 17:36 UTC by emawby

# Description
## One Line Summary
Fixing a swizzling issue where for non OneSignal notifications we were not forwarding notification opens to the app delegate remoteNotificationReceive.

## Details
We were doing this properly for OneSignal notifs but not properly for non OneSignal notifications. Now the behavior will be the same regardless of notification content/source.

### Motivation
swizzling bug

### Scope
notification opens

# Testing
## Unit testing
Added a unit test that tests forwarding opens to the app delegate selector for both OneSignal and non OneSignal payloads.

## Manual testing
tested against firebase messaging on a physical iOS device

# Affected code checklist
   - [x] Notifications
      - [ ] Display
      - [x] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2022-10-13 19:03 UTC, emawby commented on iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m
> +    [OneSignalUNUserNotificationCenter forwardReceivedNotificationResponseWithCenter:center didReceiveNotificationResponse:response OneSignalCenter:self withCompletionHandler:completionHandler];
Correct anything that we Swizzle we need to forward regardless of contents/origin. There could be other SDKs that are listening to the method or the app developer could be listening to it as well

2022-10-13 19:04 UTC, emawby commented on iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m
>      // Call orginal selector if one was set.
fixed!

2022-10-13 19:11 UTC, jkasten2 requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1131)* status: all files reviewed, 3 unresolved discussions (waiting on @emawby, @fhboswell, @jennantilla, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/UnitTests/UIApplicationDelegateSwizzlingTests.m` line 516 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1131#-NEHk8_05KtHZXXVaHw_:-NEHk8_05KtHZXXVaHwa:bgd504g) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/955599442e4b1016bdd1a7d37f94d43869b61076/iOS_SDK/OneSignalSDK/UnitTests/UIApplicationDelegateSwizzlingTests.m#L516)):*
> ```objc
> }
> 
> - (void)testNotificationOpenForwardsToLegacySelector {
> ```

Thinking we should also create a test for a non-OneSignal notification as well, to confirm the fix worked.


<!-- Sent from Reviewable.io -->

2022-10-13 19:25 UTC, fhboswell commented on iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m
> +    [OneSignalUNUserNotificationCenter forwardReceivedNotificationResponseWithCenter:center didReceiveNotificationResponse:response OneSignalCenter:self withCompletionHandler:completionHandler];
Even notifications that test true to
`![OneSignalHelper isOneSignalPayload:response.notification.request.content.userInfo]`?

So the if statement checks if the following should be run
`[OneSignalUNUserNotificationCenter processiOS10Open:response];`

Maybe invert the if statement and put `[OneSignalUNUserNotificationCenter processiOS10Open:response];` inside it.

2022-10-13 19:30 UTC, emawby reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1131)* status: all files reviewed, 3 unresolved discussions (waiting on @fhboswell, @jennantilla, @jkasten2, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/UnitTests/UIApplicationDelegateSwizzlingTests.m` line 516 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1131#-NEHk8_05KtHZXXVaHw_:-NEHoiUeEDeI81vaLB8P:bdxfr69) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/955599442e4b1016bdd1a7d37f94d43869b61076/iOS_SDK/OneSignalSDK/UnitTests/UIApplicationDelegateSwizzlingTests.m#L516)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Thinking we should also create a test for a non-OneSignal notification as well, to confirm the fix worked.
</blockquote></details>

The first notification in the test is a Onesignal notification the second one is a non Onesignal notification


<!-- Sent from Reviewable.io -->

2022-10-13 19:57 UTC, emawby commented on iOS_SDK/OneSignalSDK/Source/UNUserNotificationCenter+OneSignal.m
> +    [OneSignalUNUserNotificationCenter forwardReceivedNotificationResponseWithCenter:center didReceiveNotificationResponse:response OneSignalCenter:self withCompletionHandler:completionHandler];
good call. I inverted the check

2022-10-13 20:00 UTC, fhboswell approved these changes

2022-10-14 23:12 UTC, jkasten2 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1131)* status: all files reviewed, 3 unresolved discussions (waiting on @emawby, @fhboswell, @jennantilla, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/UnitTests/UIApplicationDelegateSwizzlingTests.m` line 516 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1131#-NEHk8_05KtHZXXVaHw_:-NENimFK9BEnGIrgmhfY:bnprdlp) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/955599442e4b1016bdd1a7d37f94d43869b61076/iOS_SDK/OneSignalSDK/UnitTests/UIApplicationDelegateSwizzlingTests.m#L516)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

The first notification in the test is a Onesignal notification the second one is a non Onesignal notification
</blockquote></details>

ah my bad, looked it too quick! It would be easier to read if this was two different tests, but that improvement that optional for this PR.


<!-- Sent from Reviewable.io -->

2022-10-17 17:52 UTC, merged