Live Activity Support WiP
OneSignal/OneSignal-iOS-SDK pull request #1152
Opened 2022-11-15 18:32 UTC by fhboswell

# READ AND DELETE THIS SECTION BEFORE SUBMITTING PR
* **Fill out each _REQUIRED_ section**
* **Fill out _OPTIONAL_ sections, remove section if it doesn't apply to your PR**
* **Read and fill out each of the checklists below**
* **Remove this section after reading**

# Description
## One Line Summary
**REQUIRED** - Very short description that summaries the changes in this PR.

## Details

### Motivation
**REQUIRED -** Why is this code change being made? Or what is the goal of this PR? Examples: Fixes a specific bug, provides additional logging to debug future issues, feature to allow X.

### Scope
**RECOMMEND - OPTIONAL -** What is intended to be effected. What is known not to change. Example: Notifications are grouped when parameter X is set, not enabled by default.

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Example: Tested opening a notification while the app was foregrounded, app build with Android Studio 2020.3 with a fresh install of the OneSignal example app on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2022-11-15 23:10 UTC, emawby requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @fhboswell, @jennantilla, @jkasten2, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m` line 500 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxWstF6lIDAnfqqML3:-NGxWstF6lIDAnfqqML4:bx12poi) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m#L500)):*
> ```objc
>                      appId:(NSString * _Nonnull)appId
>                 activityId:(NSString * _Nonnull)activityId
>                      token:(NSString * _Nullable)token {
> ```

Design question - Are we sure the token should be nullable? Is this so that folks can track a live activity with OneSignal even if they aren't updating it via push?
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.h` line 298 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxXFlc2LAgMW3xzI3e:-NGxXFlc2LAgMW3xzI3f:bmss72w) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L298)):*
> ```objc
> 
> #pragma mark Live Activity
> typedef void (^OSLiveActivitySuccessBlock)();
> ```

Design question - Is there any server response info we want to pass as a parameter to this? My gut reaction is that there isn't, but thought I would ask.
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.m` line 671 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxYLTW9R0Qq8SyJCiY:-NGxYLTW9R0Qq8SyJCiZ:b-rcdhc4) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L671)):*
> ```objc
> }
> + (void)enterLiveActivity:(NSString * _Nonnull)activityId withToken:(NSString * _Nullable)token withSuccess:(OSLiveActivitySuccessBlock _Nullable)successBlock withFailure:(OSLiveActivityFailureBlock _Nullable)failureBlock{
>     
> ```

We probably want to check privacy consent here (see sendTags for an example)
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.m` line 672 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxXeDMDC9KNX8ydsj_:-NGxXeDMDC9KNX8ydsja:b1vsyuo) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L672)):*
> ```objc
> + (void)enterLiveActivity:(NSString * _Nonnull)activityId withToken:(NSString * _Nullable)token withSuccess:(OSLiveActivitySuccessBlock _Nullable)successBlock withFailure:(OSLiveActivityFailureBlock _Nullable)failureBlock{
>     
>     [OneSignalClient.sharedClient executeRequest:[OSRequestLiveActivityEnter withUserId:self.currentSubscriptionState.userId appId:appId activityId:activityId token:token]
> ```

What happens if we don't have the userId yet? We should probably queue it up as a pending call to make once register user has finished successfully. See tags as an example.
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.m` line 685 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxYbAM5eI0EYAyaH-B:-NGxYbAM5eI0EYAyaH-C:b-c4rsi1) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L685)):*
> ```objc
> 
> + (void)exitLiveActivity:(NSString * _Nonnull)activityId withSuccess:(OSLiveActivitySuccessBlock _Nullable)successBlock withFailure:(OSLiveActivityFailureBlock _Nullable)failureBlock{
> ```

same comments for Exit as in Enter


<!-- Sent from Reviewable.io -->

2022-11-15 23:15 UTC, jkasten2 requested changes

2022-11-15 23:15 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignal.h
> ++ (void)enterLiveActivity:(NSString * _Nonnull)activityId withToken:(NSString * _Nullable)token;
`token` should be `_Nonnull`, as it is required.

2022-11-15 23:15 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignal.h
> ++ (void)enterLiveActivity:(NSString * _Nonnull)activityId withToken:(NSString * _Nullable)token withSuccess:(OSLiveActivitySuccessBlock _Nullable)successBlock withFailure:(OSLiveActivityFailureBlock
same `_Nonnull` as noted above.

2022-11-15 23:15 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/UnitTests/RequestTests.m
> +
nit, remove extra added line.

2022-11-15 23:15 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m
> +                activityId:(NSString * _Nonnull)activityId{
nit, should be a space after `activityId` and before `{`

2022-11-15 23:31 UTC, fhboswell reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @emawby, @fhboswell, @jennantilla, @jkasten2, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m` line 500 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxWstF6lIDAnfqqML3:-NGxapIS6xZE6K85Yvpv:b-xqiez0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m#L500)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Design question - Are we sure the token should be nullable? Is this so that folks can track a live activity with OneSignal even if they aren't updating it via push?
</blockquote></details>

It should not be nullable
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.h` line 298 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxXFlc2LAgMW3xzI3e:-NGxZd_21YScdSH0XOqh:bm1avd0) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L298)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Design question - Is there any server response info we want to pass as a parameter to this? My gut reaction is that there isn't, but thought I would ask.
</blockquote></details>

Neither API endpoint has anything data in the response, see tech spec.
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.h` line 301 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGwZ8rsf03GFXoHo7Sh-r1-301:-NGxaU1Z7MG0p_VCScg7:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L301)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`token` should be `_Nonnull`, as it is required.
</blockquote></details>

Done.
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.h` line 302 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGwZ8rsf03GFXoHo7Sh-r1-302:-NGxaUUg9n_Q7foqbvqV:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.h#L302)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

same `_Nonnull` as noted above.
</blockquote></details>

Done.
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.m` line 671 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGxYLTW9R0Qq8SyJCiY:-NGxcSnnE1OwxrpPmyYH:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e3a4435e95939a68a2a382f61a808c5c69a1d795/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L671)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

We probably want to check privacy consent here (see sendTags for an example)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 01:27 UTC, emawby approved these changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jennantilla, @jkasten2, and @nan-li)



<!-- Sent from Reviewable.io -->

2022-11-16 02:00 UTC, jkasten2 requested changes
> Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152)* status: all files reviewed, 2 unresolved discussions (waiting on @fhboswell, @jennantilla, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m` line 500 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGy8cezAS5LOAMZqq0W:-NGy8cezAS5LOAMZqq0X:bgntf1r) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/63a1b9c8828216a2b54be7f1d9bb475aeffa2de5/iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m#L500)):*
> ```objc
>                      appId:(NSString * _Nonnull)appId
>                 activityId:(NSString * _Nonnull)activityId
>                      token:(NSString * _Nullable)token {
> ```

token here should be `_Nonnull`.
___
*[`iOS_SDK/OneSignalSDK/Source/OneSignal.m` line 722 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGy9Mc5A-0uTXes14u3:-NGy9Mc6E8N-ESZIrAIA:b-qpf3gu) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/63a1b9c8828216a2b54be7f1d9bb475aeffa2de5/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L722)):*
> ```objc
> 
> + (void)executePendingLiveActivityUpdates{
>     if(pendingLiveActivityUpdates.count <= 0){
> ```

nit, missing spaces which doesn't match the rest of the formatting. Here as well as a few other places.


<!-- Sent from Reviewable.io -->

2022-11-16 16:14 UTC, fhboswell reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jennantilla, @jkasten2, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m` line 500 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-NGy8cezAS5LOAMZqq0W:-NH0BJNSERLo3Sb3W1tg:bb6un1j) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/63a1b9c8828216a2b54be7f1d9bb475aeffa2de5/iOS_SDK/OneSignalSDK/OneSignalCore/Source/API/OSRequests.m#L500)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

token here should be `_Nonnull`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-11-16 16:18 UTC, fhboswell reviewed
> Dismissed @jkasten2 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @jennantilla, @jkasten2, and @nan-li)



<!-- Sent from Reviewable.io -->

2022-11-16 17:53 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1152#-:-NH0Zlk1B74FlkFPtEJy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jennantilla and @nan-li)



<!-- Sent from Reviewable.io -->

2022-11-16 18:26 UTC, merged