[user model] `InAppMessages` namespace
OneSignal/OneSignal-iOS-SDK pull request #1172
Opened 2022-12-06 05:43 UTC by nan-li

# READ AND DELETE THIS SECTION BEFORE SUBMITTING PR
* **Fill out each _REQUIRED_ section**
* **Fill out _OPTIONAL_ sections, remove section if it doesn't apply to your PR**
* **Read and fill out each of the checklists below**
* **Remove this section after reading**

# Description
## One Line Summary
**REQUIRED** - Very short description that summaries the changes in this PR.

## Details

### Motivation
**REQUIRED -** Why is this code change being made? Or what is the goal of this PR? Examples: Fixes a specific bug, provides additional logging to debug future issues, feature to allow X.

### Scope
**RECOMMEND - OPTIONAL -** What is intended to be effected. What is known not to change. Example: Notifications are grouped when parameter X is set, not enabled by default.

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Example: Tested opening a notification while the app was foregrounded, app build with Android Studio 2020.3 with a fresh install of the OneSignal example app on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2022-12-07 23:20 UTC, jkasten2 requested changes

2022-12-07 23:20 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignal.h
> ++ (void)setInAppMessageClickHandler:(OSInAppMessageClickBlock _Nullable)block;
Now that this is under the `InAppMessage` namespace this should just be `setClickHandler`.

2022-12-07 23:20 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignal.h
> ++ (void)setInAppMessageLifecycleHandler:(NSObject<OSInAppMessageLifecycleHandler> *_Nullable)delegate;
Now that this is under the `InAppMessage` namespace this should just be `setLifecycleHandler`.

2022-12-07 23:20 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OSMessagingController.m
> +//    return ![self.seenInAppMessages containsObject:message.messageId] &&
Why was this commented out? Don't we need to keep this logic so triggers work?

2022-12-07 23:20 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignalInAppMessaging.m
> ++ (void)setInAppMessageClickHandler:(OSInAppMessageClickBlock)block {
Same as comments above, can be drop `InAppMessage` from the name, since it is under this new class.

2022-12-07 23:20 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignalInAppMessaging.m
> ++ (void)setInAppMessageLifecycleHandler:(NSObject<OSInAppMessageLifecycleHandler> *_Nullable)delegate; {
Same as comments above, can be drop `InAppMessage` from the name, since it is under this new class.

2022-12-07 23:33 UTC, emawby reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1172)* status: 3 of 23 files reviewed, 5 unresolved discussions (waiting on @fhboswell, @jennantilla, and @jkasten2)

___
*[`iOS_SDK/OneSignalSDK/Source/OSMessagingController.m` line 572 at r3](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1172#-NI_xPAzyrcBLDkuueJo-r3-572:-NIivpEM1FoJEDojt2t-:b-xwl6rv) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/8dd9a4b7cd9bf62ea79138b2f2e19856739d71be/iOS_SDK/OneSignalSDK/Source/OSMessagingController.m#L572)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Why was this commented out? Don't we need to keep this logic so triggers work?
</blockquote></details>

added this back but instead of isRegisterUserFinished we are just checking if we have the push subscription


<!-- Sent from Reviewable.io -->

2022-12-08 00:22 UTC, nan-li commented
> I see a number of `respondsToSelector:@selector` checks on `OSNotificationsManager.delegate` 
> 
> However as far as I can tell all methods on this protocol are required. And we are not swizzling or doing anything dynamic here, `OSNotificationsManager` is our class, so it seems like we can remove these checks from what I can tell.

True, I added these back when the delegate could be null, just a null check would be sufficient.

2022-12-08 05:40 UTC, jkasten2 approved these changes
> Reviewed 8 of 11 files at r2, 4 of 8 files at r3, 3 of 4 files at r4, 2 of 3 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @fhboswell, @jennantilla, and @nan-li)

___
*[`iOS_SDK/OneSignalSDK/Source/OSMessagingController.m` line 192 at r8](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/1172#-NIkESiR-nKSIw8d4-RP:-NIkESiR-nKSIw8d4-RQ:b2r5f8f) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/44d5657684730ec440f69b7f84f0d216ecde1d12/iOS_SDK/OneSignalSDK/Source/OSMessagingController.m#L192)):*
> ```objc
>     [OneSignalClient.sharedClient executeRequest:request onSuccess:^(NSDictionary *result) {
>         [OneSignalLog onesignalLog:ONE_S_LL_VERBOSE message:@"getInAppMessagesFromServer success"];
>         if (result[@"in_app_messages"]) { // when there are no IAMs, will this still be there?
> ```

Yes, just updated our doc to define it should always be there. If there are no IAMs then it will be an empty array.


<!-- Sent from Reviewable.io -->

2022-12-08 18:00 UTC, merged