WiP User model modularize location and InAppMessages
OneSignal/OneSignal-iOS-SDK pull request #1273
Opened 2023-06-21 19:24 UTC by emawby

# Description
## One Line Summary
Move location and InAppMessages to their own framework

## Details
Create separate frameworks for location and InAppMessages
OneSignalFramework will not directly depend on these relying on the App to include them.
The public api protocols for these have been moved to OneSignalCore along with stub implementations that will be used if the frameworks are not included.
This is currently using NSClassForString along with performSelector/NSInvocation to call into the libraries from the OneSignalFramework. This could be cleaned up in the future to use dependency injection instead.
### Motivation
Modularize IAMs and Location so that customers can exclude them from their apps. This will help with app store rejections due to these features.

### Scope
- InAppMessages: This code has moved to its own framework. It also has an indirect dependency on OneSignalLocation and uses NSInvocation to prompt for location.
- Location: This code has moved to its own framework.
- Migrations: In App Message migrations have been moved to the OneSignalInAppMessages framework.
- Lifecycle controller: This class calls location `onFocus` and InAppMessages `appDidBecomeActive`
- Sessions: Moved session time to `OSSessionManager` from `OneSignal`

### OPTIONAL - Other
**OPTIONAL -** Feel free to add any other sections or sub-sections that can explain your PR better.

# Testing
## Unit testing
**OPTIONAL -**  Explain unit tests added, if not clear in the code.

## Manual testing
**RECOMMEND - OPTIONAL -** Explain what scenarios were tested and the environment.
Example: Tested opening a notification while the app was foregrounded, app build with Android Studio 2020.3 with a fresh install of the OneSignal example app on a Pixel 6 with Android 12.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [ ] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [ ] I have included test coverage for these changes, or explained why they are not needed
   - [ ] All automated tests pass, or I explained why that is not possible
   - [ ] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [ ] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [ ] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

2023-07-13 01:01 UTC, jkasten2 requested changes
Code changes themselves look good, however there are a number of wrong copyrights with "Hiptic" on new files that need to be corrected.
Branch also contained rebuilt frameworks which made it harder to read what changed.

2023-07-13 19:49 UTC, emawby commented on iOS_SDK/OneSignalSDK/OneSignalCore/Source/OSStubLocation.m
> +//  Copyright © 2023 Hiptic. All rights reserved.
Done!

2023-07-13 19:49 UTC, emawby commented on iOS_SDK/OneSignalSDK/OneSignal.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSHumanReadableCopyright = "Copyright © 2023 Hiptic. All rights reserved.";
Done!

2023-07-13 19:49 UTC, emawby commented on iOS_SDK/OneSignalSDK/OneSignal.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSHumanReadableCopyright = "Copyright © 2023 Hiptic. All rights reserved.";
Done!

2023-07-14 19:53 UTC, jkasten2 approved these changes

2023-07-17 16:43 UTC, merged