Always send external id auth
OneSignal/OneSignal-iOS-SDK pull request #813
Opened 2020-11-24 01:53 UTC by Jeasmine

* External id auth hash should be sent in all players and on_session calls

2020-11-24 23:00 UTC, jkasten2 requested changes

2020-11-25 21:05 UTC, Jeasmine commented on iOS_SDK/OneSignalSDK/Source/OneSignal.m
> +        delayedExternalIdParameters = [OneSignalSetEmailParameters withEmail:externalId withAuthToken:hashToken withSuccess:successBlock withFailure:failureBlock];
yeah but didnt wwant to make the change on master, I was pallning on renaming this class under the major release banch. Altough this is something not used by the user, we could rename it under master branch to something like OneSignalSetAuthParams withName:name withAuthToken:hashToken withSuccess:successBlock withFailure:failureBlock

2020-11-25 21:33 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OneSignal.m
> +        delayedExternalIdParameters = [OneSignalSetEmailParameters withEmail:externalId withAuthToken:hashToken withSuccess:successBlock withFailure:failureBlock];
Ah I see where it the `email` property is being read here and assigning it to `setExternalUserId`.
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/813/files/dc06a4ac6532a83a8282438c7d19ea84d56cebd7#diff-d5a48640d81279fceea25a2bb1138a95303c65f68e0fa7041817f470a2334106R856

This looks like it gives us the correct values in the REST API calls but this field re-use is super confusing as it looks broken at first glance. I would expect `OneSignalSetEmailParameters` to have an `externaluserId` field.

Anyway it seems the flow in general is so much different in the major release it isn't feasible to make it the same between them.

Even after the major release the 2.x.x branch will be used for a while in live apps and may need to create a few release from it for any critical issues. So my suggestion is we leave a comment on both this line and the one above of this field reuse so it doesn't look like a bug in the short to mid term future.

2020-12-02 01:17 UTC, jkasten2 approved these changes

2020-12-02 14:53 UTC, merged