Creation of Channel States
OneSignal/OneSignal-iOS-SDK pull request #857
Opened 2021-01-14 19:00 UTC by Jeasmine

This PR is focused on removing channel server requests from OneSignal.m.

This is based on the first phase of SMS integration refactor.
OSStateSynchronizer will handle all the channel requests.
OSUserStateSynchronizer will be a bridge to the server requests.
OSUserState will handle all the registration data.
OSLocationState will handle user location data for registration.

It is recommended to review commit by commit.

2021-01-15 19:40 UTC, jkasten2 approved these changes

2021-01-19 18:38 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OSUserStateSynchronizer.m
> +#define mustOverride() @throw [NSException exceptionWithName:NSInvalidArgumentException reason:[NSString stringWithFormat:@"%s must be overridden in a subclass/category", __PRETTY_FUNCTION__] userInf
`mustOverride()` is already defined in two other .m files. Recommend we move this to a header file to be shared.
[Github search references](https://github.com/OneSignal/OneSignal-iOS-SDK/search?q=mustOverride)

Some recommendations that come to mind are:
1. Add to `OneSignalHelper.h`
2. Make a new `.h` file to put generic macro helpers; such as `OSMacros.h`

Feel free to fixup in this PR or make a new PR on top of `feature/decouple-player-calls` if it is easier.

2021-01-21 00:21 UTC, emawby requested changes
> Reviewed 2 of 29 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/857)* status: 3 of 29 files reviewed, 3 unresolved discussions (waiting on @gonzalonarbaiz and @Jeasmine)

___
*[iOS_SDK/OneSignalSDK/Source/OSUserStateSynchronizer.h, line 33 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/857#-MRXHMDwDIls9Okitk4o:-MRXHMDwDIls9Okitk4p:b-3lyz2o) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e7bd4df4f98f3959ca42beafd9f140745d111456/iOS_SDK/OneSignalSDK/Source/OSUserStateSynchronizer.h#L33)):*
> ```
> #ifndef OSUserStateSynchronizer_h
> #define OSUserStateSynchronizer_h
> ```
The headers don't need these defines
___
*[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 2749 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/857#-MRXHw3KDbWbMOw8rOMf:-MRXHw3KDbWbMOw8rOMg:b-bjr12s) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/670c21aade47bb0bc21a17e532980787f06fb781/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L2749)):*
> ```objc
>     // 1. Init OneSignal
>     [UnitTestCommonMethods initOneSignal_andThreadWait];
>     
> ```

I am getting Unit Tests failing consistently when running locally
testSubscriptionChangeObserverBasic
testSubscriptionChangeObserverWhenPromptNotShown
testRegistersAfterNoApnsResponse
testProvisionalPermissionState

Are these passing for you?


<!-- Sent from Reviewable.io -->

2021-01-21 14:55 UTC, Jeasmine commented
> > Reviewed 2 of 29 files at r1, 1 of 4 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/857)_ status: 3 of 29 files reviewed, 3 unresolved discussions (waiting on @gonzalonarbaiz and @Jeasmine)
> 
> _[iOS_SDK/OneSignalSDK/Source/OSUserStateSynchronizer.h, line 33 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/857#-MRXHMDwDIls9Okitk4o:-MRXHMDwDIls9Okitk4p:b-3lyz2o) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/e7bd4df4f98f3959ca42beafd9f140745d111456/iOS_SDK/OneSignalSDK/Source/OSUserStateSynchronizer.h#L33)):_
> 
> > ```
> > #ifndef OSUserStateSynchronizer_h
> > #define OSUserStateSynchronizer_h
> > ```
> 
> The headers don't need these defines
> 
> _[iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m, line 2749 at r2](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/857#-MRXHw3KDbWbMOw8rOMf:-MRXHw3KDbWbMOw8rOMg:b-bjr12s) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/670c21aade47bb0bc21a17e532980787f06fb781/iOS_SDK/OneSignalSDK/UnitTests/UnitTests.m#L2749)):_
> 
> > ```objc
> >     // 1. Init OneSignal
> >     [UnitTestCommonMethods initOneSignal_andThreadWait];
> >     
> > ```
> 
> I am getting Unit Tests failing consistently when running locally
> testSubscriptionChangeObserverBasic
> testSubscriptionChangeObserverWhenPromptNotShown
> testRegistersAfterNoApnsResponse
> testProvisionalPermissionState
> 
> Are these passing for you?

Yeah, these are failing now, I checked on https://github.com/OneSignal/OneSignal-iOS-SDK/pull/858, and in that PR, the tests are not failing. I Will check if something on the rebase broke this

2021-01-21 19:45 UTC, jkasten2 commented on iOS_SDK/OneSignalSDK/Source/OSUserStateSynchronizer.m
> +#define mustOverride() @throw [NSException exceptionWithName:NSInvalidArgumentException reason:[NSString stringWithFormat:@"%s must be overridden in a subclass/category", __PRETTY_FUNCTION__] userInf
Thanks for the improvement, I see `OSMacros.h` in commit 897cece00a5f1d351fa0e85c0a95949c28a76136

2021-01-21 19:50 UTC, jkasten2 approved these changes

2021-01-22 14:26 UTC, Jeasmine commented
@emawby core problem was fixed under https://github.com/OneSignal/OneSignal-iOS-SDK/pull/862

2021-01-25 18:19 UTC, emawby approved these changes

2021-02-02 19:44 UTC, merged