Added timezone id to user data
OneSignal/OneSignal-iOS-SDK pull request #866
Opened 2021-02-02 17:26 UTC by gonzalonarbaiz

Added timezone_id to user data to be sent.

2021-02-05 18:25 UTC, emawby approved these changes

2021-02-09 16:13 UTC, Jeasmine requested changes
LGTM just need a test as on Android

2021-02-16 21:42 UTC, jkasten2 requested changes
* Needs a test added
* Needs a rebase as there is a mere conflict

2021-02-18 18:15 UTC, emawby approved these changes

2021-02-19 18:31 UTC, merged