Crashfix: save IAM to redisplay in correct format on clear cache.
OneSignal/OneSignal-iOS-SDK pull request #884
Opened 2021-02-17 10:40 UTC by escfrya

Crash fix for [Issue 848](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/848)

2021-03-02 01:29 UTC, emawby commented
Hello! Thank you for the contribution. This change looks correct but we also need to update the unit test for this behavior if you don't mind. If you run the tests you should see that `testIAMRemoveFromCache_Redisplay` is failing. We need to update the save and gets to use the CodeableData instead of Dictionary for key. 
`[standardUserDefaults saveCodeableDataForKey:OS_IAM_REDISPLAY_DICTIONARY withValue:redisplayedInAppMessages];`

`NSMutableDictionary <NSString *, OSInAppMessage *> *redisplayMessagesCache = [standardUserDefaults getSavedCodeableDataForKey:OS_IAM_REDISPLAY_DICTIONARY defaultValue:nil];`

2021-03-02 01:29 UTC, emawby requested changes
waiting for unit test update

2021-03-03 06:54 UTC, escfrya commented
@emawby Hello! Done

2021-03-10 10:00 UTC, jkasten2 commented
Thanks for the PR, we followed up with PR #894 address the reminding work.

2021-03-10 10:00 UTC, closed without merging