Fix testBasicInitTest and testInitOnSimulator failing tests
OneSignal/OneSignal-iOS-SDK pull request #905
Opened 2021-03-17 13:03 UTC by Jeasmine

* Tests were failing due to missind device_type under push channel

2021-03-17 20:39 UTC, jkasten2 requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine)

___
*[iOS_SDK/OneSignalSDK/Source/OSUserStatePushSynchronizer.m, line 74 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905#-MW0uKzh7iq6RZuCiSk9:-MW0uKzi469RZtsdaxXl:bsunsmk) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/57a7a038710d5968e5a00647078806b09d469eb9/iOS_SDK/OneSignalSDK/Source/OSUserStatePushSynchronizer.m#L74)):*
> ```objc
>     NSMutableDictionary *pushDataDic = (NSMutableDictionary *)[registrationState.toDictionary mutableCopy];
>     pushDataDic[@"identifier"] = _currentSubscriptionState.pushToken;
>     pushDataDic[@"device_type"] = self.getDeviceType;
> ```

PR notes only fixing tests but this is a change to the main source. Did missing this create any issue outside of tests?


<!-- Sent from Reviewable.io -->

2021-03-18 17:11 UTC, Jeasmine reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905)* status: all files reviewed, 1 unresolved discussion (waiting on @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OSUserStatePushSynchronizer.m, line 74 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905#-MW0uKzh7iq6RZuCiSk9:-MW5JEHyDVzSlGAgtK6v:b-t1ztr3) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/57a7a038710d5968e5a00647078806b09d469eb9/iOS_SDK/OneSignalSDK/Source/OSUserStatePushSynchronizer.m#L74)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

PR notes only fixing tests but this is a change to the main source. Did missing this create any issue outside of tests?
</blockquote></details>

No, actually, you are right. The commit message should indicate that the device type is missing from the push channel


<!-- Sent from Reviewable.io -->

2021-03-18 17:18 UTC, jkasten2 approved these changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-03-18 17:19 UTC, jkasten2 approved these changes
Would be good to note the side effects of what this fixes too in the PR notes. (more than the tests)

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905#-:-MW5LGSXCGKkQS406pPl:b-yubl1c)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)



<!-- Sent from Reviewable.io -->

2021-03-18 17:39 UTC, Jeasmine commented
> Would be good to note the side effects of what this fixes too in the PR notes. (more than the tests)
> 
> > _[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/905#-:-MW5LGSXCGKkQS406pPl:b-yubl1c)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine)

updated!

2021-03-18 17:40 UTC, merged