Always create new player ids on app install
OneSignal/OneSignal-iOS-SDK pull request #914
Opened 2021-04-09 18:14 UTC by emawby

This pr removes the usage of identifierForVendor to prevent creating a new player id for a reinstalled app.

2021-04-09 18:25 UTC, jkasten2 requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby and @Jeasmine)

___
*[iOS_SDK/OneSignalSDK/Source/OSUserState.h, line 37 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914#-MXrsNlP5mr943ajjTYG:-MXrsNlP5mr943ajjTYH:b-61m7dx) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/5f071c0728a0611294dac37637e5f81ea257cb0f/iOS_SDK/OneSignalSDK/Source/OSUserState.h#L37)):*
> ```objc
> @property (strong, nonatomic, readwrite, nullable) NSString *timezoneId;
> //This property is no longer being populated with vendor id
> @property (strong, nonatomic, readwrite, nullable) NSString *adId;
> ```

Can we just delete the property completely?


<!-- Sent from Reviewable.io -->

2021-04-09 22:43 UTC, emawby reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @Jeasmine and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OSUserState.h, line 37 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914#-MXrsNlP5mr943ajjTYG:-MXsnCVHD4xEGAtuV5lx:b88eok9) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/5f071c0728a0611294dac37637e5f81ea257cb0f/iOS_SDK/OneSignalSDK/Source/OSUserState.h#L37)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Can we just delete the property completely?
</blockquote></details>

I was concerned about wrappers expecting it but it looks like they never access it so I removed it completely


<!-- Sent from Reviewable.io -->

2021-04-10 02:01 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914#-:-MXtVhPjCPnXWJj1giLz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine and @jkasten2)



<!-- Sent from Reviewable.io -->

2021-04-12 17:39 UTC, emawby reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine and @jkasten2)

___
*[iOS_SDK/OneSignalSDK/Source/OSUserState.h, line 37 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/914#-MXrsNlP5mr943ajjTYG:-MY69jKiEKU6w7A04ngl:b-896fix) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/5f071c0728a0611294dac37637e5f81ea257cb0f/iOS_SDK/OneSignalSDK/Source/OSUserState.h#L37)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

I was concerned about wrappers expecting it but it looks like they never access it so I removed it completely
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-12 17:39 UTC, merged