Fixed Pre-existing Notification Delegate
OneSignal/OneSignal-iOS-SDK pull request #924
Opened 2021-05-12 01:33 UTC by tanaynigam

This happens when another library's delegate is loaded before OneSignal's delegate code.
This commit solves it by reassigning the pre loaded delegate into swizzle in OneSignal's  methods.
This issue was discovered through a Unity issue where Unity Mobile Notification Services would load their delegate before OneSignal's delegate.
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/245

2021-05-12 19:10 UTC, emawby requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/924)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jkasten2 and @tanaynigam)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 627 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/924#-M_Wz20lEWHXGsCmkVFK:-M_Wz20lEWHXGsCmkVFL:bpp5v00) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d6bc8ce03644b7481a3dc838c4ad3ebdbca88592/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L627)):*
> ```objc
>          This swizzles in the OneSignal methods into the existing non-OneSignal delegate.
>          */
>         curNotifCenter.delegate = curNotifCenter.delegate;
> ```

Nice find! @jkasten2 is there a way to unit test this on the native side?


<!-- Sent from Reviewable.io -->

2021-05-12 20:29 UTC, jkasten2 reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/924)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @emawby)

___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 627 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/924#-M_Wz20lEWHXGsCmkVFK:-M_XDKFFEiiGnHlj5WKI:b-3z420t) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d6bc8ce03644b7481a3dc838c4ad3ebdbca88592/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L627)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Nice find! @jkasten2 is there a way to unit test this on the native side?
</blockquote></details>

I see a test called `testZSwizzling` which does something close to what we need to test here. However there is a comment on this there is test carry over. I think we could clean this up and make a working test with some work.

Since this PR is on the 2.x.x branch I think we should omit the test in this PR. We can focus on creating a test on the master branch PR when we create it.


<!-- Sent from Reviewable.io -->

2021-05-13 19:51 UTC, jkasten2 commented
___
*[iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m, line 627 at r1](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/924#-M_Wz20lEWHXGsCmkVFK:-M_bH7CU1WTDQFi0WvsG:b-p1zko4) ([raw file](https://github.com/onesignal/onesignal-ios-sdk/blob/d6bc8ce03644b7481a3dc838c4ad3ebdbca88592/iOS_SDK/OneSignalSDK/Source/OneSignalHelper.m#L627)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I see a test called `testZSwizzling` which does something close to what we need to test here. However there is a comment on this there is test carry over. I think we could clean this up and make a working test with some work.

Since this PR is on the 2.x.x branch I think we should omit the test in this PR. We can focus on creating a test on the master branch PR when we create it.
</blockquote></details>

Added tests to this PR on master:
https://github.com/OneSignal/OneSignal-iOS-SDK/pull/926


<!-- Sent from Reviewable.io -->

2021-05-14 20:14 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-ios-sdk/924#-:-M_gW1WsDcUut3S8FjY_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby)



<!-- Sent from Reviewable.io -->

2021-05-14 20:16 UTC, merged